#11 - 01
estoque = ["calça","camisa","short","saia"]
print("Antes: ",estoque)
estoque.append("casaco")
print("Depois: ",estoque)
estoque.sort()
print("Depois do SORT: ",estoque)
estoque.sort(reverse = "True")
print("Depois do SORT REVERSE: ",estoque)
estoque.insert(3,"cinto")
print("Depois do INSERT",estoque)
estoque.remove("calça")
print("Depois do REMOVE",estoque)
print("\n\n")
estoque.append("parafuso")
print("ERRADO:",estoque)
backup = estoque.pop()
print("Depois do POP",estoque)
print("item  removido: ",backup)
print("\n\n")
